variables:
  PRE_COMMIT_VERSION: "1.15.1"

image: jonatkinson/python-poetry:3.7

stages:
  - check
  - build
  - test

check:
  stage: check
  before_script:
    - pip install pre-commit==$PRE_COMMIT_VERSION
  script:
    - make -s check

build:
  stage: build
  artifacts:
    paths:
      - ~/.cache/pypoetry/virtualenvs
  script:
    - poetry install

unit-test:
  stage: test
  script:
    - poetry run pytest tests
