variables:
  PRE_COMMIT_VERSION: "1.15.1"

image: jonatkinson/python-poetry:3.7

before_script:
  - poetry config settings.virtualenvs.create true
  - poetry config settings.virtualenvs.in-project true

# Find out poetry in-project dir
after_script:
  - ls -al

stages:
  - check
  - build
  - test

check:
  stage: check
  before_script:
    - pip install pre-commit==$PRE_COMMIT_VERSION
  script:
    - make -s check

build:
  stage: build
  artifacts:
    paths:
      - .venv/
  script:
    - poetry install

unit-test:
  stage: test
  script:
    - poetry run pytest tests
