variables:
  PRE_COMMIT_VERSION: "1.15.1"

image: jonatkinson/python-poetry:3.7

before_script:
    # gitlab cannot pickup absolute path, hence use a local virtualenv
  - poetry config settings.virtualenvs.in-project true

stages:
  - check
  - build
  - test
  - build-artifacts

check:
  stage: check
  before_script:
    - pip install pre-commit==$PRE_COMMIT_VERSION
  script:
    - make -s check

build:
  stage: build
  artifacts:
    expire_in: 1 hour
    paths:
      - .venv/
  script:
    - poetry install

unit-test:
  stage: test
  script:
    - poetry run pytest tests/unit

integration-test:
  stage: test
  script:
    - poetry run pytest tests/torch_integration

build-doc:
  stage: build-artifacts
  script:
    - make -s docs
  only:
    refs:
      - master