variables:
  PRE_COMMIT_VERSION: "1.15.1"

image: jonatkinson/python-poetry:3.7

before_script:
    # gitlab cannot pickup absolute path, hence use a local virtualenv
  - poetry config settings.virtualenvs.in-project true

stages:
  - check
  - build
  - test
  - deploy

check:
  stage: check
  before_script:
    - pip install pre-commit==$PRE_COMMIT_VERSION
  script:
    - make -s check

build:
  stage: build
  artifacts:
    expire_in: 3 hours
    paths:
      - .venv/
  script:
    - poetry install

unit-test:
  stage: test
  script:
    - poetry run pytest tests/unit

integration-test:
  stage: test
  script:
    - poetry run pytest tests/torch_integration

pages:
  image: dacit/sphinx-doc-extended:1.2.1
  stage: deploy
  script:
    - make -sC docs html
    - if [[ "$CI_COMMIT_REF_NAME" = "master" && "$CI_COMMIT_TAG" = "" ]]; then
        mkdir -p public/latest;
        rm -rf public/latest;
        mv docs/build/html public/latest;
      elif [[ $CI_COMMIT_TAG =~ ^release-[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
        mkdir -p public/$CI_COMMIT_TAG;
        mv -T docs/build/html public/$CI_COMMIT_TAG;
        echo '<head><meta http-equiv="refresh" content="0; url='"$CI_COMMIT_TAG"'/index.html"></head><body><p><a href="'"$CI_COMMIT_TAG"'/index.html">Redirect</a></p></body>' > index.html;
      fi;
  cache:
    paths:
      - public
  artifacts:
    paths:
      - public
  only:
    - master
    - release